# Site
name: "Startup Sutra"
title: "Startup Sutra"
description: "A guide for Startup Enthusiasts! Be the Mythical 10x Engineer, the unstoppable Unicorn named Product Engineer!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://microstartup-ideas.github.io/product-engg-blog'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sajal:
    name: Sajal Sharma
    display_name: Sajal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: 6bikramsuthar@gmail.com
    web: https://cosmos-sajal.github.io/
    twitter: https://twitter.com/thebstar13
    description: "Founding Member @ Orange Health, IIIT Hyderabad Post Graduate, Startup Enthusiast"
  bikram:
    name: Bikram Sutar
    display_name: Bikram    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.linkedin.com/in/thebstar/
    twitter: https://twitter.com/wowthemesnet
    description: "Building Houseware. Led App and Web at OrangeHealth & Radicali. Technical writer, mostly working with react, typescript & Javascript. Views just mine."
"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
